wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704725763.308697
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.11.6
      5: 0.15.12
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Train loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
