wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704463854.298695
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.11.5
      5: 0.16.1
      6: 4.34.1
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Train loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: Validation loss
      5: 1
      6:
      - 1
